language: node_js
node_js:
  - '0.12'
  - 'iojs'

before_install:
  - 'npm install chai@"$CHAI_VERSION"'
env:
  - 'CHAI_VERSION=2.0.0'
  - 'CHAI_VERSION=3.0.0'
  - 'CHAI_VERSION=^2.0'
  - 'CHAI_VERSION=^3.0'
